spectaql:
  displayAllServers: true
  themeDir: ./theme

introspection:
  introspectionFile: spec.json
  removeTrailingPeriodFromDescriptions: false
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: Title
  description: Description

servers:
  - url: https://swapi-graphql.netlify.app/.netlify/functions/index
    description: Staging
