spectaql:
  displayAllServers: true

introspection:
  introspectionFile: spec.json
  removeTrailingPeriodFromDescriptions: false
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: Star Wars API Reference
  description: May the force be with you

servers:
  - url: https://swapi-graphql.netlify.app/.netlify/functions/index
    description: Staging
